name = "toonstream-api"
main = "src/worker.js"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
account_id = "cd4ab75cca150f63177325a6bb1c355f"


[observability]
enabled = true
